sudo: required

env:
  global:
    - VERSION=2.6.2

services:
  - docker

install:
  - docker build . -t savingsutd/gcp-ruby:$VERSION

script:
  - docker run gcp-ruby:$VERSION bash -c "which ruby || (printf 'ruby not found.'; exit 1)"
  - docker run gcp-ruby:$VERSION bash -c "which bundle || (printf 'bundle ot found.'; exit 1)"
  - docker run gcp-ruby:$VERSION bash -c "which gcloud || (printf 'gcloud not found.'; exit 1)"
  - docker run gcp-ruby:$VERSION bash -c "test -f ~/cloud_sql_proxy || (printf 'cloud_sql_proxy not found.'; exit 1)"
  - docker run gcp-ruby:$VERSION bash -c "which node || (printf 'node not found.'; exit 1)"
  - docker run gcp-ruby:$VERSION bash -c "which yarn || (printf 'yarn not found.'; exit 1)"
  - docker run gcp-ruby:$VERSION bash -c "touch /cloudsql/test.txt && rm /cloudsql/test.txt"

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh $VERSION
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh latest
    on:
      branch: master

notifications:
  slack:
    secure: Rm8uAPsrhzjQWsDDslfs+L7dBZde49+NrtfjVNwgrAMbTFksgm6QScKahXpAVTlVcS/+eI95/L5zyuikZt8FyyMGXmIIiPHPgHvbeDlU6HXg4ln9HJRC9lVSqsT17iFiuEcznywt678USxq75vpPIUZarcGFQGlYwZlzcuaMmnHgeejPcL0HI2pKaYNpZe9eaxMEHSqgrK9jwJeOxjEo+Oc09jDh3hAlgai5lTbJ1tRnSKVlgFR63WQ9Md7e5IqsVABf+Pr6qNiqhdkwIvTGfeCqbWFz7+Fo+yzTuCdV4VJwGQtJ3TPHpmUheW111K5977Nqrd5dZuzpuITEBmJN/eF3YsqKi+qOCizk+lz2l4qjoEtzJQ1C80WnH3GJc+3tTeM6FmJOZ7xasYwQhBteDiOrMA/lBoMcD0ELFxO9IaOj6VoYuPKoYO5itfW+nEm+9dOdR59Z4+CFg8isdVM9bq4Oi9LS8IsHDxz+36poqt0Ew6MM1MB9TsWpYSJFXXlYjw0kydzJmwsSk1mOUQv4+ZfKcfOFrt56u2Nq7zpjoF8EJ9izbKG4Tos2CwF3GGy/UEjHguPz4JWSlEyA6zVnAEVQEJ9UAh46qbK6ylyCtaiWfPdjfySt+PMnFwB5w1mJYi1LTC80cKmG2Q4lgyBqCh7x2ClU4TtiXCJZqNSO9nc=
