name: Build and Publish
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: docker://replicated/dockerfilelint:09a5034
        with:
          args: /Dockerfile
