name: Build and Publish
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm i
      - run: npm test
  build:
    needs: lint
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker build -t gcp-ruby .
  test:
    needs: build
    name: Test Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Test Ruby
        run: docker run gcp-ruby bash -c "which ruby || exit 1"
