name: Build and Publish
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm i
      - run: npm test
  build:
    needs: lint
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/docker/cli@master
        with:
          args: build -t gcp-ruby .
