name: Build and Publish
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm i -g dockerlint
      - run: dockerlint Dockerfile
